version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    volumes:
      - openwebui-data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  db:
    build: .
    restart: always
    environment:
      POSTGRES_DB: ghdemo44
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: gnusolidario
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./install_demo_database.sh:/docker-entrypoint-initdb.d/install_demo_database.sh
    ports:
    - "5432:5432"  # Exposing PostgreSQL to the host

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  openwebui-data:
  pgdata: