version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.5.18
    container_name: openwebui
    ports:
      - "3000:8080"
    volumes:
      - openwebui-data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  db:
    build: .
    restart: always
    environment:
      POSTGRES_DB: ghdemo44
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: gnusolidario
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./install_demo_database.sh:/docker-entrypoint-initdb.d/install_demo_database.sh
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"    # Redis server
      - "8001:8001"    # Redis Stack UI
    volumes:
      - redis-data:/data

volumes:
  openwebui-data:
  pgdata:
  redis-data:
